config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
    resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
  has_many :doses
  has_many :ingredients, through: :doses, dependent: :destroy
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :ingredient, uniqueness: { scope: :cocktail }
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  # before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end
  def new
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def create
    cocktail = Cocktail.create(cocktail_params)
    redirect_to cocktail_path(cocktail)
  end

  private

  # def set_cocktail
  #   @cocktail = Cocktail.find(params[:id])
  # end
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def show
    @dose = Dose.find(params[:id])
  end

  def create
    cocktail = Cocktail.find(params[:cocktail_id])
    dose = Dose.new(dose_params)
    dose.cocktail_id = cocktail.id
    if dose.save
      redirect_to cocktail_path(cocktail)
    end
  end

  def destroy
    dose = Dose.find(params[:id])
    dose.destroy
    redirect_to cocktail_path(dose.cocktail)
  end

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1555195040-3f37d4a2f385?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=900&q=60);">
  <div class="container">
    <h1>Cheers to life!</h1>
    <p>  </p>
    <%= link_to "add a new cocktail", new_cocktail_path, class: 'btn btn-light' %>
  </div>
</div>

  <div class="cards" >
    <% @cocktails.each do |cocktail| %>
      <% if cocktail.photo.attached? %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
        <h2><%= link_to cocktail.name, cocktail_path(cocktail)%></h2>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/cocktails/new.html.erb
<div class="background-img">
  <div class="form">
  <h3>create a new cocktail now</h3>
    <%= simple_form_for(@cocktail) do |f| %>
        <%= f.input :name%>
        <%= f.input :photo, as: :file %>
        <%= f.submit "add", class: "btn btn-outline-dark btn-lg" %>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "back to all cocktails", cocktails_path, class: 'btn btn-outline-dark btn-lg' %>
    <%= link_to "add details", new_cocktail_dose_path(@cocktail, @dose), class: 'btn btn-outline-dark btn-lg' %>
</div>
<div class="wrapper">
  <div class="show" style="background-image: url('<%= cl_image_path @cocktail.photo.key %>')">
    <h3 style="color :white; font-weight: bold"><%= @cocktail.name %></h3>
  </div>
<ul>
  <% @cocktail.doses.each do |d| %>
  <li>
    Ingredients: <%= d.ingredient.name %>
    <%= link_to dose_path(d), method: :delete do %>
      <%= '🗑' %>
    <% end %>
  </li>
  <% end %>
</ul>
</div>

app/views/doses/new.html.erb
<div class="background-img page_wrapper">
  <div class="form">
    <h3>add doses now</h3>
    <div>
      <%= simple_form_for([@cocktail, @dose]) do |f| %>
      <%= f.input :description %>
      <%= f.association :ingredient %>
      <%= f.submit "add", class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMinisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

</head>

<body>
  <%= yield %>
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>
</html>